---
- name: Build EE environments
  ansible.builtin.include_tasks: 00_build_ee.yml
  loop: "{{ ee_list }}"
  loop_control:
    loop_var: __execution_environment_definition

- name: Push to controller
  tags:
    - set_stats
  block:
    - ansible.builtin.set_stats:
        data:
          execution_environments: "{{ ee_list | community.general.json_query(q) }}"
      vars:
        q: >
          [?ee_create].{
            create: ee_create,
            name: name,
            organization: ee_organization,
            pull: ee_pull,
            image: join(':',[name, tag])
          }
...
