---
namespace: escwq
name: ee_utilities
version: 0.0.2
description: A collection of utility roles for usage with Ansible Execution Enviroments
readme: README.md
authors:
    - Sean Sullivan @sean-m-sullivan
    - Anshul Behl @anshulbehl
    - Homero Pawlowski @homeski
repository: https://github.com/homeski/ee_utilities
issues: https://github.com/homeski/ee_utilities/issues
build_ignore:
    - galaxy.yml.j2
    - release.yml
    - .github
    - .markdownlint.yml
    - .ansible-lint
    - .yamllint.yml
    - .pre-commit-config.yaml
    - .gitignore
    - .gitattributes
license:
    - GPL-3.0-or-later
tags:
    - execution
    - enviroments
    - collection
    - utilities
    - utils
    - ee_utilities
    - ee_utils
dependencies:
    "containers.podman": ">=1.0.0"
...
